name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: javac HelloWorld.java
      - run: echo "Compiled"
  execute:
    runs-on: ubuntu-latest
    steps:
      - run: java HelloWorld

