name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  compile-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: javac HelloWorld.java
      - run: echo "Compiled"
  execute-job:
    needs: compile-job
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: HelloWorld.class
          path: HelloWorld.class
      - run: java HelloWorld

