name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: javac HelloWorld.java
      - run: echo "Compiled"

